spring.application.name=backend
spring.data.mongodb.uri=${MONGODB_URI}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
cloudinary.upload-preset=pilates-exercicios
